# Generated by Django 4.2.1 on 2023-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='end_date',
            field=models.DateField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journey',
            name='start_date',
            field=models.DateField(),
        ),
    ]
