# Generated by Django 4.2.2 on 2023-08-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.journey')),
            ],
        ),
    ]
