# Generated by Django 4.2.1 on 2023-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_journey_end_date_alter_journey_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='start_date',
            field=models.DateField(),
        ),
    ]
