# Generated by Django 4.2.1 on 2023-08-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_journey_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='start_date',
        ),
    ]
