# Generated by Django 4.2.1 on 2023-08-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_journey_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='created',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='updated',
        ),
    ]
